# Template

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scienceplots

plt.style.use('science')
plt.rcParams.update({'font.size': 14})

In [4]:
deg_to_rad = lambda deg: 2*np.pi*deg / 360

# Gitterkonstante bestimmen

In [10]:
angle_left = np.array([42.8, 42.9, 42.8, 42.9, 42.9])
angle_right = 360 - np.array([318.1, 318.2, 318.3, 318.2, 318.2])
delta_angle = 0.1

angle_left = deg_to_rad(angle_left)
angle_right = deg_to_rad(angle_right)
delta_angle = deg_to_rad(delta_angle)

n = 2 # 2. Beugungsmaximum
lambda_Na1 = 588.995 #nm
lambda_Na2 = 589.592 #nm 

g11 = n*lambda_Na1 / np.sin(angle_left)
g12 = n*lambda_Na2 / np.sin(angle_left)
g21 = n*lambda_Na1 / np.sin(angle_right)
g22 = n*lambda_Na2 / np.sin(angle_right)

print(g11, g11 / np.tan(angle_left)* delta_angle)
print(g12, g12 / np.tan(angle_left)* delta_angle)
print(g21, g21 / np.tan(angle_right)* delta_angle)
print(g22, g22 / np.tan(angle_right)* delta_angle)
print(1/570 * 10**6)

[1733.76271447 1730.50372585 1733.76271447 1730.50372585 1730.50372585] [3.26776847 3.25022857 3.26776847 3.25022857 3.25022857]
[1735.52004066 1732.25774876 1735.52004066 1732.25774876 1732.25774876] [3.27108065 3.25352298 3.27108065 3.25352298 3.25352298]
[1763.9002327  1767.3407562  1770.80013225 1767.3407562  1767.3407562 ] [3.43114092 3.44992787 3.46884625 3.44992787 3.44992787]
[1765.68810601 1769.13211679 1772.59499924 1769.13211679 1769.13211679] [3.43461869 3.45342469 3.47236224 3.45342469 3.45342469]
1754.3859649122808


# Wellenlänge bestimmen Gitter

In [12]:
g = 1754.386 #nm
dg = 3.4
delta_angle = 0.1

def lambda_color(color_angle, d_angle):
    ang = deg_to_rad(color_angle)
    l = g * np.sin(ang)   
    dl = np.sin(ang)*dg + g*np.cos(ang)*deg_to_rad(d_angle)
    return l, dl

lila_l  = np.array([13.2, 13.2, 13.3])
blau_l  = np.array([14.3, 14.2, 14.3])
dgrün_l = np.array([16.1, 16.0, 16.2])
hgrün_l = np.array([18.0, 18.1, 17.9])
gelb_l  = np.array([19.2, 19.1, 19.1])

colors_l = [lila_l, blau_l, dgrün_l, hgrün_l, gelb_l]

lila_r = np.array([346.5, 346.6, 346.6])
blau_r = np.array([345.5, 345.5, 345.4])
dgrün_r = np.array([343.6, 343.5, 343.6])
hgrün_r = np.array([341.8, 341.7, 341.7])
gelb_r = np.array([340.6, 340.6, 340.7])

colors_r = [lila_r, blau_r, dgrün_r, hgrün_r, gelb_r]

for col in colors_l:
    l, dl = lambda_color(col, delta_angle)
    print(l, dl)

print('---------------------------------------')

for col in colors_r:
    l, dl = lambda_color(360 - col, delta_angle)
    print(l, dl)

[400.61556961 400.61556961 403.59603823] [3.75747326 3.75747326 3.76202452]
[433.33160993 430.36384348 433.33160993] [3.8069046  3.80246855 3.8069046 ]
[486.51694535 483.57431812 489.45809056] [3.88475753 3.88053226 3.88897098]
[542.13508869 545.04637867 539.22214728] [3.96277496 3.96676117 3.95877668]
[576.95904091 574.06650092 574.06650092] [4.0098093  4.00595667 4.00595667]
---------------------------------------
[409.55327811 406.57527742 406.57527742] [3.77109266 3.76656433 3.76656433]
[439.26317379 439.26317379 442.22695313] [3.81574189 3.81574189 3.82014311]
[495.3358991  498.27254453 495.3358991 ] [3.89736231 3.90154018 3.89736231]
[547.95600835 550.86396885 550.86396885] [3.97073529 3.97469732 3.97469732]
[582.73883952 582.73883952 579.84982337] [4.0174779  4.0174779  4.01364971]


# Prisma Winkelmessung

In [14]:
angle_left = np.array([64.8, 64.8, 64.7, 64.7, 64.9])
angle_right = 360 - np.array([305.3, 305.2, 305.3, 305.3, 305.4])
delta_angle = 0.1

#angle_left = deg_to_rad(angle_left)
#angle_right = deg_to_rad(angle_right)
#delta_angle = deg_to_rad(delta_angle)

gamma = (angle_left + angle_right)/2
d_gamma = 2*delta_angle
print(gamma, d_gamma)

[59.75 59.8  59.7  59.7  59.75] 0.2


# Prisma Wellenlänge

In [ ]:
delta_angle = 0.1
lila_full = np.array([285.9, 286.0, 286.0, 285.9, 284.1])
blue_angle = np.array([288.0, 283.3, 288.5])
dgrün_angel = np.array([290.5, 290.8, 291.1]) 
hgrün_angel = np.array([291.9, 292.3, 292.8]) 
yellow_full = np.array([292.6, 292.9, 293.5, 292.8, 293.5]) 
lila2 = np.array([286.2])
rot1 = np.array([294.2])
rot2 = np.array([295.0])

colors_list = [lila2, lila_full, blue_angle, dgrün_angel, hgrün_angel, yellow_full, rot1, rot2]
colors_plot = []